-- =========================
-- Domain: access control and sharing
-- =========================

CREATE TABLE IF NOT EXISTS acl (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NULL,
    folder_id BIGINT NULL,
    user_id BIGINT NULL,
    group_id BIGINT NULL,
    permission VARCHAR(100) NOT NULL,
    permission_role VARCHAR(50) NOT NULL DEFAULT 'viewer',
    can_preview BOOLEAN NOT NULL DEFAULT TRUE,
    can_download BOOLEAN NOT NULL DEFAULT TRUE,
    can_save BOOLEAN NOT NULL DEFAULT FALSE,
    can_share BOOLEAN NOT NULL DEFAULT FALSE,
    expire_at TIMESTAMP NULL,
    granted_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_acl_file FOREIGN KEY (file_id) REFERENCES "file"(file_id) ON DELETE CASCADE,
    CONSTRAINT fk_acl_folder FOREIGN KEY (folder_id) REFERENCES folder(folder_id) ON DELETE CASCADE,
    CONSTRAINT fk_acl_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_acl_group FOREIGN KEY (group_id) REFERENCES user_group(id) ON DELETE CASCADE,
    CONSTRAINT fk_acl_granted_by FOREIGN KEY (granted_by) REFERENCES "user"(user_id) ON DELETE SET NULL,
    CONSTRAINT chk_acl_subject_exactly_one CHECK (num_nonnulls(user_id, group_id) = 1),
    CONSTRAINT chk_acl_resource_exactly_one CHECK (num_nonnulls(file_id, folder_id) = 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_acl_file_user
    ON acl (file_id, user_id)
    WHERE file_id IS NOT NULL AND user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_acl_file_group
    ON acl (file_id, group_id)
    WHERE file_id IS NOT NULL AND group_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_acl_folder_user
    ON acl (folder_id, user_id)
    WHERE folder_id IS NOT NULL AND user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_acl_folder_group
    ON acl (folder_id, group_id)
    WHERE folder_id IS NOT NULL AND group_id IS NOT NULL;

CREATE TRIGGER trg_acl_updated_at
BEFORE UPDATE ON acl
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS share (
    share_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    file_id BIGINT NULL,
    folder_id BIGINT NULL,
    share_link VARCHAR(255) NOT NULL UNIQUE,
    share_code VARCHAR(64) NOT NULL,
    status share_status_enum NOT NULL DEFAULT 'active',
    share_type VARCHAR(50) NOT NULL DEFAULT 'public',
    permission_role VARCHAR(50) NOT NULL DEFAULT 'viewer',
    allow_preview BOOLEAN NOT NULL DEFAULT TRUE,
    allow_download BOOLEAN NOT NULL DEFAULT TRUE,
    allow_save BOOLEAN NOT NULL DEFAULT FALSE,
    allow_reshare BOOLEAN NOT NULL DEFAULT FALSE,
    require_login BOOLEAN NOT NULL DEFAULT FALSE,
    max_visits INTEGER NULL,
    max_downloads INTEGER NULL,
    password_hash VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_accessed_at TIMESTAMP NULL,
    expire_time TIMESTAMP NULL,
    visit_count INTEGER NOT NULL DEFAULT 0,
    download_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_share_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_share_file FOREIGN KEY (file_id) REFERENCES "file"(file_id) ON DELETE CASCADE,
    CONSTRAINT fk_share_folder FOREIGN KEY (folder_id) REFERENCES folder(folder_id) ON DELETE CASCADE,
    CONSTRAINT chk_share_target CHECK (num_nonnulls(file_id, folder_id) = 1),
    CONSTRAINT chk_share_limits CHECK (
        (max_visits IS NULL OR max_visits >= 0)
        AND
        (max_downloads IS NULL OR max_downloads >= 0)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_share_code ON share (share_code);
CREATE INDEX IF NOT EXISTS idx_share_user_status ON share (user_id, status);
CREATE INDEX IF NOT EXISTS idx_share_expire_time ON share (expire_time);

CREATE TRIGGER trg_share_updated_at
BEFORE UPDATE ON share
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS share_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_id BIGINT NOT NULL,
    user_id BIGINT NULL,
    group_id BIGINT NULL,
    status share_member_status_enum NOT NULL DEFAULT 'pending',
    target_folder_id BIGINT NULL,
    accepted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_share_member_share FOREIGN KEY (share_id) REFERENCES share(share_id) ON DELETE CASCADE,
    CONSTRAINT fk_share_member_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_share_member_group FOREIGN KEY (group_id) REFERENCES user_group(id) ON DELETE CASCADE,
    CONSTRAINT fk_share_member_target_folder FOREIGN KEY (target_folder_id) REFERENCES folder(folder_id) ON DELETE SET NULL,
    CONSTRAINT chk_share_member_subject_exactly_one CHECK (num_nonnulls(user_id, group_id) = 1)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_share_member_user
    ON share_member (share_id, user_id)
    WHERE user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_share_member_group
    ON share_member (share_id, group_id)
    WHERE group_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_share_member_share_status ON share_member (share_id, status);

DROP TRIGGER IF EXISTS trg_share_member_updated_at ON share_member;
CREATE TRIGGER trg_share_member_updated_at
BEFORE UPDATE ON share_member
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS favorite_item (
    favorite_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    item_type favorite_item_type_enum NOT NULL,
    file_id BIGINT NULL,
    folder_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_favorite_item_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_favorite_item_file FOREIGN KEY (file_id) REFERENCES "file"(file_id) ON DELETE CASCADE,
    CONSTRAINT fk_favorite_item_folder FOREIGN KEY (folder_id) REFERENCES folder(folder_id) ON DELETE CASCADE,
    CONSTRAINT chk_favorite_item_target_exactly_one CHECK (num_nonnulls(file_id, folder_id) = 1),
    CONSTRAINT chk_favorite_item_type_match CHECK (
        (item_type = 'file' AND file_id IS NOT NULL AND folder_id IS NULL)
        OR
        (item_type = 'folder' AND folder_id IS NOT NULL AND file_id IS NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_favorite_item_file
    ON favorite_item (user_id, file_id)
    WHERE file_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_favorite_item_folder
    ON favorite_item (user_id, folder_id)
    WHERE folder_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS user_folder_preference (
    preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    folder_id BIGINT NULL,
    view_mode view_mode_enum NOT NULL DEFAULT 'list',
    sort_by sort_by_enum NOT NULL DEFAULT 'name',
    sort_direction sort_direction_enum NOT NULL DEFAULT 'asc',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_folder_preference_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_folder_preference_folder FOREIGN KEY (folder_id) REFERENCES folder(folder_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_folder_preference_default
    ON user_folder_preference (user_id)
    WHERE folder_id IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_folder_preference_folder
    ON user_folder_preference (user_id, folder_id)
    WHERE folder_id IS NOT NULL;

DROP TRIGGER IF EXISTS trg_user_folder_preference_updated_at ON user_folder_preference;
CREATE TRIGGER trg_user_folder_preference_updated_at
BEFORE UPDATE ON user_folder_preference
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS share_access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_id BIGINT NOT NULL,
    user_id BIGINT NULL,
    event_type VARCHAR(20) NOT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(255) NULL,
    result VARCHAR(20) NOT NULL DEFAULT 'success',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_share_access_log_share FOREIGN KEY (share_id) REFERENCES share(share_id) ON DELETE CASCADE,
    CONSTRAINT fk_share_access_log_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_share_access_log_share_created_at
    ON share_access_log (share_id, created_at DESC);
