<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useDebounceFn } from '@vueuse/core';
import type { ContentItem } from '../../types/file';
import type { Collaborator, Share } from '../../types/share';
import type { PermissionItem } from '../../types/permission';
import type { User, UserGroup } from '../../types/user';
import { createShare, deleteShare, getShares, updateShareSettings } from '../../api/share';
import { getUsers } from '../../api/user';
import { getUserGroups } from '../../api/usergroup';
import { createPermission, deletePermission, getPermissions, updatePermission } from '../../api/permission';
import { useLocaleStore } from '../../store/locale';
import { ui } from '../../utils/ui';

type SharePermission = 'read' | 'write' | 'admin';

interface ShareSettingsDraft {
  passwordProtected: boolean;
  password: string;
  expireAt: string;
  allowDownload: boolean;
  allowPreview: boolean;
}

interface ShareApplyResult {
  autoGeneratedPassword: string | null;
}

interface Props {
  isVisible: boolean;
  itemToShare: ContentItem | null;
}

const props = defineProps<Props>();
const emit = defineEmits(['close']);
const localeStore = useLocaleStore();
const t = localeStore.t;

const searchKeyword = ref('');
const searchResults = ref<Collaborator[]>([]);
const collaborators = ref<Collaborator[]>([]);
const isSearching = ref(false);
const isSubmitting = ref(false);

const initialCollaborators = ref<Collaborator[]>([]);
const initialShare = ref<Share | null>(null);

const publicLinkEnabled = ref(false);
const currentShareLink = ref('');
const settingsMessage = ref('');

const createDefaultSettings = (): ShareSettingsDraft => ({
  passwordProtected: false,
  password: '',
  expireAt: '',
  allowDownload: true,
  allowPreview: true,
});

const shareSettings = ref<ShareSettingsDraft>(createDefaultSettings());

const currentItemPayload = computed(() => {
  if (!props.itemToShare) return null;

  if (props.itemToShare.itemType === 'file') {
    return { fileId: props.itemToShare.id };
  }

  return { folderId: props.itemToShare.id };
});

const publicLink = computed(() => {
  if (!currentShareLink.value) return '';
  return `${window.location.origin}/share/${currentShareLink.value}`;
});

const cloneCollaborator = (collaborator: Collaborator): Collaborator => ({
  id: collaborator.id,
  name: collaborator.name,
  type: collaborator.type,
  email: collaborator.email,
  avatar: collaborator.avatar,
  permission: collaborator.permission,
  permissionId: collaborator.permissionId,
});

const collaboratorKey = (collaborator: Pick<Collaborator, 'type' | 'id'>): string =>
  `${collaborator.type}:${collaborator.id}`;

const normalizePermission = (permission: Collaborator['permission']): SharePermission =>
  permission || 'read';

const hydrateShareSettings = (share: Share | null) => {
  if (!share) {
    shareSettings.value = createDefaultSettings();
    return;
  }

  shareSettings.value = {
    passwordProtected: share.settings.passwordProtected,
    password: share.settings.password || '',
    expireAt: share.settings.expireAt ? share.settings.expireAt.slice(0, 10) : '',
    allowDownload: share.settings.allowDownload,
    allowPreview: share.settings.allowPreview,
  };
};

const fetchPermissions = async (): Promise<Collaborator[]> => {
  if (!currentItemPayload.value) return [];

  try {
    const response = await getPermissions({ ...currentItemPayload.value, page: 1, perPage: 50 });
    return response.items.map((permission: PermissionItem) => ({
      id: permission.grantedTo.id,
      name: permission.grantedTo.name,
      type: permission.grantedTo.type,
      permission: permission.permission,
      permissionId: permission.permissionId,
    }));
  } catch (error) {
    console.error('Failed to fetch permissions', error);
    return [];
  }
};

const loadExistingShare = async (): Promise<Share | null> => {
  if (!props.itemToShare) return null;

  try {
    const response = await getShares({ page: 1, perPage: 100 });
    return (
      response.items.find(
        (item) => item.itemType === props.itemToShare?.itemType && item.itemInfo.id === props.itemToShare?.id,
      ) || null
    );
  } catch (error) {
    console.error('Failed to load existing share', error);
    return null;
  }
};

const resetDraft = (nextCollaborators: Collaborator[], share: Share | null) => {
  initialCollaborators.value = nextCollaborators.map(cloneCollaborator);
  collaborators.value = nextCollaborators.map(cloneCollaborator);
  initialShare.value = share;
  currentShareLink.value = share?.shareLink || '';
  publicLinkEnabled.value = Boolean(share);
  hydrateShareSettings(share);
  searchKeyword.value = '';
  searchResults.value = [];
  settingsMessage.value = '';
};

const refreshDialogState = async () => {
  const [permissionList, share] = await Promise.all([fetchPermissions(), loadExistingShare()]);
  resetDraft(permissionList, share);
};

const searchCollaborators = async (keyword: string) => {
  const query = keyword.trim();
  if (!query) {
    searchResults.value = [];
    return;
  }

  isSearching.value = true;
  try {
    const [users, groups] = await Promise.all([
      getUsers({ search: query, page: 1, perPage: 8 }),
      getUserGroups({ search: query, page: 1, perPage: 8 }),
    ]);

    const userResults: Collaborator[] = users.items.map((user: User) => ({
      id: user.userId,
      name: user.username,
      type: 'user',
      email: user.email,
    }));

    const groupResults: Collaborator[] = groups.items.map((group: UserGroup) => ({
      id: group.groupId,
      name: group.name,
      type: 'group',
    }));

    const existingIds = new Set(collaborators.value.map((item) => collaboratorKey(item)));
    searchResults.value = [...userResults, ...groupResults].filter((item) => !existingIds.has(collaboratorKey(item)));
  } finally {
    isSearching.value = false;
  }
};

const debouncedSearch = useDebounceFn(searchCollaborators, 260);

const addCollaborator = (target: Collaborator) => {
  if (isSubmitting.value) return;
  const key = collaboratorKey(target);
  if (collaborators.value.some((item) => collaboratorKey(item) === key)) {
    return;
  }

  collaborators.value.push({
    ...cloneCollaborator(target),
    permission: 'read',
  });

  searchKeyword.value = '';
  searchResults.value = [];
};

const changePermission = (collaborator: Collaborator, permission: SharePermission) => {
  if (isSubmitting.value) return;
  collaborator.permission = permission;
};

const removeCollaborator = (collaborator: Collaborator) => {
  if (isSubmitting.value) return;
  collaborators.value = collaborators.value.filter((item) => collaboratorKey(item) !== collaboratorKey(collaborator));
};

const copyPassword = async () => {
  if (!shareSettings.value.password) return;
  try {
    await navigator.clipboard.writeText(shareSettings.value.password);
    settingsMessage.value = t('share.dialog.settings.passwordCopied');
  } catch {
    await ui.copyText({
      title: t('share.dialog.copyPassword.title'),
      message: t('share.dialog.copyPassword.message'),
      text: shareSettings.value.password,
    });
  }
};

const clearExpireDate = () => {
  if (isSubmitting.value) return;
  shareSettings.value.expireAt = '';
};

const copyLink = async () => {
  if (!publicLink.value) return;

  try {
    await navigator.clipboard.writeText(publicLink.value);
    settingsMessage.value = t('share.dialog.settings.linkCopied');
  } catch {
    await ui.copyText({
      title: t('share.dialog.copyLink.title'),
      message: t('share.dialog.copyLink.message'),
      text: publicLink.value,
    });
  }
};

const buildShareSettingsPayload = () => {
  const trimmedPassword = shareSettings.value.password.trim();
  const shouldAutoGeneratePassword = shareSettings.value.passwordProtected && !trimmedPassword;
  const payload: Record<string, string | boolean | null> = {
    passwordProtected: shareSettings.value.passwordProtected,
    allowDownload: shareSettings.value.allowDownload,
    allowPreview: shareSettings.value.allowPreview,
    expireAt: shareSettings.value.expireAt ? `${shareSettings.value.expireAt}T23:59:59.000Z` : null,
  };

  if (shareSettings.value.passwordProtected && trimmedPassword) {
    payload.password = trimmedPassword;
  }

  return { payload, shouldAutoGeneratePassword };
};

const hasSettingsChanged = (before: Share, after: ShareSettingsDraft): boolean => {
  const beforeExpireAt = before.settings.expireAt ? before.settings.expireAt.slice(0, 10) : '';
  if (before.settings.passwordProtected !== after.passwordProtected) return true;
  if (before.settings.allowDownload !== after.allowDownload) return true;
  if (before.settings.allowPreview !== after.allowPreview) return true;
  if (beforeExpireAt !== after.expireAt) return true;
  if (after.passwordProtected && after.password.trim()) return true;
  return false;
};

const applyCollaboratorChanges = async () => {
  const payloadBase = currentItemPayload.value;
  if (!payloadBase) return;

  const initialMap = new Map(initialCollaborators.value.map((item) => [collaboratorKey(item), item]));
  const draftMap = new Map(collaborators.value.map((item) => [collaboratorKey(item), item]));

  for (const initialItem of initialCollaborators.value) {
    const key = collaboratorKey(initialItem);
    if (draftMap.has(key)) continue;
    if (!initialItem.permissionId) continue;
    await deletePermission(initialItem.permissionId);
  }

  for (const draftItem of collaborators.value) {
    const key = collaboratorKey(draftItem);
    const initialItem = initialMap.get(key);
    if (!initialItem) {
      await createPermission({
        ...payloadBase,
        userId: draftItem.type === 'user' ? draftItem.id : undefined,
        groupId: draftItem.type === 'group' ? draftItem.id : undefined,
        permission: normalizePermission(draftItem.permission),
      });
      continue;
    }

    if (!initialItem.permissionId) continue;
    if (normalizePermission(initialItem.permission) === normalizePermission(draftItem.permission)) continue;

    await updatePermission(initialItem.permissionId, { permission: normalizePermission(draftItem.permission) });
  }
};

const applyShareChanges = async (): Promise<ShareApplyResult> => {
  if (!props.itemToShare) {
    return { autoGeneratedPassword: null };
  }

  if (!publicLinkEnabled.value) {
    if (initialShare.value?.shareLink) {
      await deleteShare(initialShare.value.shareLink);
      currentShareLink.value = '';
    }
    return { autoGeneratedPassword: null };
  }

  let shareLink = initialShare.value?.shareLink || '';
  if (!shareLink) {
    const created = await createShare({
      resourceType: props.itemToShare.itemType,
      resourceId: props.itemToShare.id,
    });
    shareLink = created.shareLink;
    currentShareLink.value = created.shareLink;
  }

  if (initialShare.value && !hasSettingsChanged(initialShare.value, shareSettings.value)) {
    return { autoGeneratedPassword: null };
  }

  const { payload, shouldAutoGeneratePassword } = buildShareSettingsPayload();
  const updated = await updateShareSettings(shareLink, payload);
  currentShareLink.value = updated.shareLink;
  const issuedPassword = updated.settings.password?.trim() || '';
  if (issuedPassword) {
    shareSettings.value.password = issuedPassword;
    settingsMessage.value = t('share.dialog.settings.passwordUpdated');
  }
  return {
    autoGeneratedPassword: shouldAutoGeneratePassword && issuedPassword ? issuedPassword : null,
  };
};

const handleDone = async () => {
  if (isSubmitting.value) return;
  settingsMessage.value = '';

  if (initialShare.value?.shareLink && !publicLinkEnabled.value) {
    const confirmed = await ui.confirm({
      title: t('share.dialog.confirmRevoke.title'),
      message: t('share.dialog.confirmRevoke.message'),
      confirmText: t('share.dialog.confirmRevoke.confirm'),
      danger: true,
    });
    if (!confirmed) return;
  }

  isSubmitting.value = true;
  try {
    await applyCollaboratorChanges();
    const shareResult = await applyShareChanges();
    if (shareResult.autoGeneratedPassword) {
      await ui.copyText({
        title: t('share.dialog.generatedPassword.title'),
        message: t('share.dialog.generatedPassword.message'),
        text: shareResult.autoGeneratedPassword,
      });
    }
    emit('close');
  } catch (error) {
    console.error('Failed to submit share changes', error);
    settingsMessage.value = t('share.dialog.settings.saveFailed');
    await refreshDialogState();
  } finally {
    isSubmitting.value = false;
  }
};

const handleClose = () => {
  if (isSubmitting.value) return;
  emit('close');
};

watch(
  () => props.isVisible,
  async (visible) => {
    if (!visible) return;
    await refreshDialogState();
  },
);

watch(
  () => shareSettings.value.passwordProtected,
  (enabled) => {
    if (!enabled) {
      shareSettings.value.password = '';
    }
  },
);

</script>

<template>
  <transition name="modal-fade">
    <div v-if="isVisible" class="modal-overlay" @click.self="handleClose">
      <div class="modal-dialog" :class="{ 'modal-dialog--busy': isSubmitting }">
        <header class="modal-header">
          <div>
            <h3 class="modal-title">{{ t('share.dialog.title').replace('{itemName}', itemToShare?.name || '') }}</h3>
            <p class="subtitle">{{ t('share.dialog.subtitle') }}</p>
          </div>
          <button class="modal-close" :disabled="isSubmitting" @click="handleClose" :aria-label="t('share.dialog.close')">x</button>
        </header>

        <div class="modal-body">
          <section class="section">
            <h4>{{ t('share.dialog.section.collaborators') }}</h4>

            <div class="search-box">
              <input
                v-model="searchKeyword"
                type="text"
                :placeholder="t('share.dialog.searchPlaceholder')"
                :disabled="isSubmitting"
                @input="debouncedSearch(searchKeyword)"
              />
              <div v-if="isSearching" class="hint">{{ t('share.dialog.searching') }}</div>
            </div>

            <div v-if="searchResults.length" class="search-list">
              <button v-for="result in searchResults" :key="`${result.type}-${result.id}`" class="search-item" :disabled="isSubmitting" @click="addCollaborator(result)">
                <span>{{ result.name }}</span>
                <small>{{ result.type === 'user' ? result.email : t('share.dialog.result.userGroup') }}</small>
              </button>
            </div>

            <div v-if="!collaborators.length" class="empty-hint">{{ t('share.dialog.emptyCollaborators') }}</div>

            <div v-else class="collaborator-list">
              <div v-for="collaborator in collaborators" :key="collaborator.permissionId || `${collaborator.type}-${collaborator.id}`" class="collaborator-item">
                <div class="collaborator-meta">
                  <strong>{{ collaborator.name }}</strong>
                  <small>{{ collaborator.type === 'user' ? collaborator.email || t('share.dialog.collaborator.user') : t('share.dialog.collaborator.group') }}</small>
                </div>

                <select
                  :value="collaborator.permission"
                  :disabled="isSubmitting"
                  @change="changePermission(collaborator, ($event.target as HTMLSelectElement).value as 'read' | 'write' | 'admin')"
                >
                  <option value="read">{{ t('share.dialog.permission.read') }}</option>
                  <option value="write">{{ t('share.dialog.permission.write') }}</option>
                  <option value="admin">{{ t('share.dialog.permission.admin') }}</option>
                </select>

                <button class="remove-btn" :disabled="isSubmitting" @click="removeCollaborator(collaborator)">{{ t('share.dialog.remove') }}</button>
              </div>
            </div>
          </section>

          <section class="section public-share">
            <div class="public-head">
              <div>
                <h4>{{ t('share.dialog.section.publicLink') }}</h4>
                <p>{{ t('share.dialog.publicDescription') }}</p>
              </div>

              <label class="switch">
                <input v-model="publicLinkEnabled" type="checkbox" :disabled="isSubmitting" />
                <span class="slider" />
              </label>
            </div>

            <div v-if="publicLinkEnabled" class="public-content">
              <template v-if="currentShareLink">
                <div class="link-row">
                  <input type="text" :value="publicLink" readonly />
                  <button :disabled="isSubmitting" @click="copyLink">{{ t('share.dialog.copy') }}</button>
                </div>
              </template>
              <div v-else class="hint">{{ t('share.dialog.pendingApplyNotice') }}</div>

              <div class="settings-grid">
                <label class="setting-check">
                  <input v-model="shareSettings.passwordProtected" type="checkbox" :disabled="isSubmitting" />
                  <span>{{ t('share.dialog.passwordProtected') }}</span>
                </label>
                <div v-if="shareSettings.passwordProtected" class="password-row">
                  <input v-model="shareSettings.password" type="text" :disabled="isSubmitting" :placeholder="t('share.dialog.passwordPlaceholder')" />
                  <button v-if="shareSettings.password" type="button" class="ghost-btn" :disabled="isSubmitting" @click="copyPassword">
                    {{ t('share.dialog.copy') }}
                  </button>
                </div>
                <label class="setting-check">
                  <input v-model="shareSettings.allowDownload" type="checkbox" :disabled="isSubmitting" />
                  <span>{{ t('share.dialog.allowDownload') }}</span>
                </label>
                <label class="setting-check">
                  <input v-model="shareSettings.allowPreview" type="checkbox" :disabled="isSubmitting" />
                  <span>{{ t('share.dialog.allowPreview') }}</span>
                </label>

                <div class="setting-date-row">
                  <label for="share-expire-date">{{ t('share.dialog.expireDate') }}</label>
                  <div class="date-input-wrap">
                    <input id="share-expire-date" v-model="shareSettings.expireAt" type="date" :disabled="isSubmitting" />
                    <button type="button" class="ghost-btn" :disabled="isSubmitting" @click="clearExpireDate">{{ t('share.dialog.clear') }}</button>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <span class="hint">{{ t('share.dialog.pendingApplyNotice') }}</span>
          <span v-if="settingsMessage" class="hint">{{ settingsMessage }}</span>
        </div>

        <footer class="modal-footer">
          <button class="done-btn" :disabled="isSubmitting" @click="handleDone">
            {{ isSubmitting ? t('share.dialog.saving') : t('share.dialog.done') }}
          </button>
        </footer>
      </div>
    </div>
  </transition>
</template>

<style scoped>
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(2, 6, 23, 0.55);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 2000;
}

.modal-dialog {
  width: min(760px, calc(100vw - 24px));
  max-height: calc(100vh - 40px);
  display: flex;
  flex-direction: column;
  border: 1px solid var(--color-border);
  border-radius: 14px;
  background-color: var(--color-bg-primary);
  box-shadow: var(--shadow-xl);
}

.modal-dialog--busy {
  cursor: progress;
}

.modal-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 12px;
  padding: 14px 16px;
  border-bottom: 1px solid var(--color-divider);
}

.modal-title {
  margin: 0;
  font-size: 17px;
}

.subtitle {
  margin: 4px 0 0;
  color: var(--color-text-tertiary);
  font-size: 12px;
}

.modal-close {
  width: 30px;
  height: 30px;
  border-radius: 8px;
  border: 1px solid var(--color-border);
  background-color: var(--color-bg-primary);
  cursor: pointer;
}

.modal-body {
  overflow: auto;
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.section {
  border: 1px solid var(--color-border);
  border-radius: 10px;
  background-color: var(--color-bg-secondary);
  padding: 12px;
}

.section h4 {
  margin: 0 0 10px;
}

.search-box input {
  width: 100%;
  height: 36px;
  border-radius: 8px;
  border: 1px solid var(--color-border);
  background-color: var(--color-bg-primary);
  padding: 0 10px;
}

.search-list {
  margin-top: 8px;
  border: 1px solid var(--color-border);
  border-radius: 8px;
  max-height: 160px;
  overflow: auto;
}

.search-item {
  width: 100%;
  border: none;
  background: transparent;
  text-align: left;
  padding: 8px 10px;
  display: flex;
  flex-direction: column;
  cursor: pointer;
}

.search-item:hover {
  background-color: var(--color-bg-tertiary);
}

.search-item small {
  color: var(--color-text-tertiary);
}

.empty-hint,
.hint {
  color: var(--color-text-tertiary);
  font-size: 13px;
}

.collaborator-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-top: 10px;
}

.collaborator-item {
  display: grid;
  grid-template-columns: 1fr 120px auto;
  gap: 8px;
  align-items: center;
  border: 1px solid var(--color-border);
  border-radius: 8px;
  padding: 8px;
  background-color: var(--color-bg-primary);
}

.collaborator-meta {
  min-width: 0;
  display: flex;
  flex-direction: column;
}

.collaborator-meta strong,
.collaborator-meta small {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.collaborator-meta small {
  color: var(--color-text-tertiary);
}

.collaborator-item select {
  height: 34px;
  border-radius: 8px;
  border: 1px solid var(--color-border);
  padding: 0 8px;
}

.remove-btn {
  height: 34px;
  border-radius: 8px;
  border: 1px solid #fca5a5;
  background-color: var(--color-danger-light);
  color: var(--color-danger-dark);
  cursor: pointer;
}

.public-share .public-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 10px;
}

.public-share .public-head p {
  margin: 4px 0 0;
  font-size: 12px;
  color: var(--color-text-tertiary);
}

.public-content {
  margin-top: 10px;
  display: grid;
  gap: 12px;
}

.link-row {
  display: grid;
  grid-template-columns: 1fr auto;
  gap: 8px;
}

.link-row input {
  height: 36px;
  border-radius: 8px;
  border: 1px solid var(--color-border);
  background-color: var(--color-bg-primary);
  padding: 0 10px;
  font-family: var(--font-family-mono);
  font-size: 12px;
}

.link-row button,
.ghost-btn {
  height: 36px;
  border-radius: 8px;
  border: 1px solid var(--color-border);
  background-color: var(--color-bg-primary);
  cursor: pointer;
  padding: 0 12px;
}

.settings-grid {
  display: grid;
  gap: 10px;
}

.setting-check {
  display: inline-flex;
  align-items: center;
  gap: 8px;
}

.setting-date-row {
  display: grid;
  gap: 6px;
}

.setting-date-row label {
  font-size: 12px;
  color: var(--color-text-secondary);
}

.date-input-wrap {
  display: grid;
  grid-template-columns: minmax(120px, 220px) auto;
  gap: 8px;
}

.date-input-wrap input {
  height: 36px;
  border-radius: 8px;
  border: 1px solid var(--color-border);
  background-color: var(--color-bg-primary);
  padding: 0 10px;
}

.password-row {
  display: grid;
  grid-template-columns: 1fr auto;
  gap: 8px;
}

.password-row input {
  height: 36px;
  border-radius: 8px;
  border: 1px solid var(--color-border);
  background-color: var(--color-bg-primary);
  padding: 0 10px;
  font-family: var(--font-family-mono);
  font-size: 12px;
}

.modal-footer {
  padding: 12px 16px;
  border-top: 1px solid var(--color-divider);
  display: flex;
  justify-content: flex-end;
}

.done-btn {
  height: 36px;
  border-radius: 8px;
  border: none;
  padding: 0 14px;
  color: var(--color-text-on-primary);
  background-color: var(--color-primary);
  cursor: pointer;
}

.switch {
  width: 44px;
  height: 24px;
  position: relative;
}

.switch input {
  opacity: 0;
  width: 0;
  height: 0;
}

.slider {
  position: absolute;
  inset: 0;
  border-radius: 999px;
  background-color: var(--color-border);
  transition: 0.2s;
}

.slider::before {
  content: '';
  position: absolute;
  width: 18px;
  height: 18px;
  left: 3px;
  top: 3px;
  border-radius: 50%;
  background-color: #fff;
  transition: 0.2s;
}

.switch input:checked + .slider {
  background-color: var(--color-primary);
}

.switch input:checked + .slider::before {
  transform: translateX(20px);
}

.modal-fade-enter-active,
.modal-fade-leave-active {
  transition: opacity 0.2s ease;
}

.modal-fade-enter-from,
.modal-fade-leave-to {
  opacity: 0;
}

@media (max-width: 760px) {
  .collaborator-item {
    grid-template-columns: 1fr;
  }

  .link-row,
  .date-input-wrap,
  .settings-actions {
    grid-template-columns: 1fr;
    display: grid;
  }
}
</style>
