-- =========================
-- Domain: agent persistence
-- =========================

CREATE TABLE IF NOT EXISTS agent_user_setting (
    setting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    default_execution_policy agent_execution_policy_enum NOT NULL DEFAULT 'confirm',
    default_data_policy_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    llm_provider VARCHAR(50) NULL,
    llm_model VARCHAR(100) NULL,
    default_budget_tokens INTEGER NOT NULL DEFAULT 20000,
    default_max_steps INTEGER NOT NULL DEFAULT 20,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_user_setting_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_agent_user_setting_default_budget_tokens CHECK (default_budget_tokens > 0),
    CONSTRAINT ck_agent_user_setting_default_max_steps CHECK (default_max_steps > 0)
);

CREATE INDEX IF NOT EXISTS idx_agent_user_setting_user_id
    ON agent_user_setting (user_id);

DROP TRIGGER IF EXISTS trg_agent_user_setting_updated_at ON agent_user_setting;
CREATE TRIGGER trg_agent_user_setting_updated_at
BEFORE UPDATE ON agent_user_setting
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS agent_mcp_server (
    mcp_server_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NULL,
    visibility agent_mcp_visibility_enum NOT NULL DEFAULT 'system',
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    endpoint VARCHAR(500) NOT NULL,
    transport VARCHAR(30) NOT NULL DEFAULT 'streamable_http',
    auth_type VARCHAR(30) NOT NULL DEFAULT 'none',
    headers_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    tool_namespace VARCHAR(100) NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_mcp_server_owner FOREIGN KEY (owner_user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_agent_mcp_server_visibility_owner CHECK (
        (visibility = 'system' AND owner_user_id IS NULL)
        OR
        (visibility = 'private' AND owner_user_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_agent_mcp_server_visibility_enabled
    ON agent_mcp_server (visibility, enabled);
CREATE INDEX IF NOT EXISTS idx_agent_mcp_server_owner_visibility
    ON agent_mcp_server (owner_user_id, visibility);

DROP TRIGGER IF EXISTS trg_agent_mcp_server_updated_at ON agent_mcp_server;
CREATE TRIGGER trg_agent_mcp_server_updated_at
BEFORE UPDATE ON agent_mcp_server
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS agent_skill (
    skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_key VARCHAR(120) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    triggers_text TEXT NULL,
    tool_whitelist_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    plan_template_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    inputs_schema_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    outputs_schema_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    visibility agent_skill_visibility_enum NOT NULL DEFAULT 'global',
    owner_user_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_skill_owner FOREIGN KEY (owner_user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT uk_agent_skill_skill_key UNIQUE (skill_key),
    CONSTRAINT ck_agent_skill_visibility_owner CHECK (
        (visibility = 'global' AND owner_user_id IS NULL)
        OR
        (visibility = 'private' AND owner_user_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_agent_skill_visibility_created_at
    ON agent_skill (visibility, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_skill_owner_visibility
    ON agent_skill (owner_user_id, visibility);
CREATE INDEX IF NOT EXISTS idx_agent_skill_search_trgm
    ON agent_skill
    USING gin ((COALESCE(name, '') || ' ' || COALESCE(description, '') || ' ' || COALESCE(triggers_text, '')) gin_trgm_ops);

DROP TRIGGER IF EXISTS trg_agent_skill_updated_at ON agent_skill;
CREATE TRIGGER trg_agent_skill_updated_at
BEFORE UPDATE ON agent_skill
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS agent_memory (
    memory_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    scope agent_memory_scope_enum NOT NULL,
    scope_key VARCHAR(255) NULL,
    kind agent_memory_kind_enum NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    source_job_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NULL,
    CONSTRAINT fk_agent_memory_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_memory_source_job FOREIGN KEY (source_job_id) REFERENCES background_job(job_id) ON DELETE SET NULL,
    CONSTRAINT ck_agent_memory_scope_key CHECK (
        (scope = 'global' AND scope_key IS NULL)
        OR
        (scope IN ('workspace', 'session') AND scope_key IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_agent_memory_user_scope
    ON agent_memory (user_id, scope, scope_key);
CREATE INDEX IF NOT EXISTS idx_agent_memory_user_expires
    ON agent_memory (user_id, expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_memory_search_trgm
    ON agent_memory
    USING gin ((COALESCE(title, '') || ' ' || COALESCE(content, '')) gin_trgm_ops);

DROP TRIGGER IF EXISTS trg_agent_memory_updated_at ON agent_memory;
CREATE TRIGGER trg_agent_memory_updated_at
BEFORE UPDATE ON agent_memory
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS agent_plan (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    input_text TEXT NOT NULL,
    context_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    execution_policy agent_execution_policy_enum NOT NULL,
    data_policy_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    chosen_skill_id VARCHAR(120) NULL,
    proposed_actions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    plan_hash VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    cost_estimate_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_plan_job FOREIGN KEY (job_id) REFERENCES background_job(job_id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_plan_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agent_plan_user_created_at
    ON agent_plan (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_plan_plan_hash
    ON agent_plan (plan_hash);

CREATE TABLE IF NOT EXISTS agent_action_log (
    action_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    step_no INTEGER NOT NULL,
    tool_name VARCHAR(120) NOT NULL,
    inputs_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    outputs_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    duration_ms INTEGER NULL,
    error_message TEXT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP NULL,
    CONSTRAINT fk_agent_action_log_job FOREIGN KEY (job_id) REFERENCES background_job(job_id) ON DELETE CASCADE,
    CONSTRAINT uk_agent_action_log_job_step UNIQUE (job_id, step_no)
);

CREATE INDEX IF NOT EXISTS idx_agent_action_log_job_started_at
    ON agent_action_log (job_id, started_at);
CREATE INDEX IF NOT EXISTS idx_agent_action_log_job_status
    ON agent_action_log (job_id, status);

CREATE TABLE IF NOT EXISTS agent_work_session (
    work_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    checkpoint_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    checkpoint_version INTEGER NOT NULL DEFAULT 0,
    last_checkpoint_at TIMESTAMP NULL,
    tool_call_count INTEGER NOT NULL DEFAULT 0,
    last_tool_started_at TIMESTAMP NULL,
    last_tool_finished_at TIMESTAMP NULL,
    last_error_message TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP NULL,
    CONSTRAINT fk_agent_work_session_job FOREIGN KEY (job_id) REFERENCES background_job(job_id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_work_session_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_agent_work_session_checkpoint_version CHECK (checkpoint_version >= 0),
    CONSTRAINT ck_agent_work_session_tool_call_count CHECK (tool_call_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_agent_work_session_user_status
    ON agent_work_session (user_id, status);
CREATE INDEX IF NOT EXISTS idx_agent_work_session_created_at
    ON agent_work_session (created_at DESC);

DROP TRIGGER IF EXISTS trg_agent_work_session_updated_at ON agent_work_session;
CREATE TRIGGER trg_agent_work_session_updated_at
BEFORE UPDATE ON agent_work_session
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
