-- =========================
-- Domain: audit, notification and risk control
-- =========================

CREATE TABLE IF NOT EXISTS "log" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    actor_type VARCHAR(50) NOT NULL DEFAULT 'user',
    operation VARCHAR(255) NOT NULL,
    target_type VARCHAR(50) NULL,
    target_id BIGINT NULL,
    result VARCHAR(20) NOT NULL DEFAULT 'success',
    request_id VARCHAR(128) NULL,
    user_agent VARCHAR(255) NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    details TEXT,
    ip_address VARCHAR(45),
    performed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_log_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_log_performed_at ON "log" (performed_at);
CREATE INDEX IF NOT EXISTS idx_log_user_operation ON "log" (user_id, operation);
CREATE INDEX IF NOT EXISTS idx_log_target ON "log" (target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_log_request_id ON "log" (request_id);

CREATE TABLE IF NOT EXISTS notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'system',
    channel VARCHAR(50) NOT NULL DEFAULT 'in_app',
    message TEXT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    sent_at TIMESTAMP NULL,
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMP NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    sender_user_id BIGINT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_sender_user FOREIGN KEY (sender_user_id) REFERENCES "user"(user_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_notification_user_status ON notification (user_id, status, is_read);
CREATE INDEX IF NOT EXISTS idx_notification_created_at ON notification (created_at);

CREATE TRIGGER trg_notification_updated_at
BEFORE UPDATE ON notification
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION sync_notification_read_at()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.is_read AND NEW.read_at IS NULL THEN
            NEW.read_at = CURRENT_TIMESTAMP;
        ELSIF NOT NEW.is_read THEN
            NEW.read_at = NULL;
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.is_read AND (OLD.is_read IS DISTINCT FROM NEW.is_read) AND NEW.read_at IS NULL THEN
        NEW.read_at = CURRENT_TIMESTAMP;
    ELSIF NOT NEW.is_read THEN
        NEW.read_at = NULL;
    ELSIF NEW.read_at IS NOT NULL THEN
        NEW.is_read = TRUE;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_notification_sync_read_at ON notification;
CREATE TRIGGER trg_notification_sync_read_at
BEFORE INSERT OR UPDATE ON notification
FOR EACH ROW
EXECUTE FUNCTION sync_notification_read_at();

CREATE TABLE IF NOT EXISTS object_scan_result (
    scan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id BIGINT NOT NULL,
    scan_type VARCHAR(50) NOT NULL,
    engine_name VARCHAR(100) NULL,
    engine_version VARCHAR(100) NULL,
    result scan_result_enum NOT NULL DEFAULT 'pending',
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    scanned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_object_scan_result_object FOREIGN KEY (object_id) REFERENCES storage_object(object_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_object_scan_result_object_scanned_at
    ON object_scan_result (object_id, scanned_at DESC);

CREATE TABLE IF NOT EXISTS moderation_case (
    case_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id BIGINT NOT NULL,
    file_id BIGINT NULL,
    reason_type VARCHAR(50) NOT NULL,
    confidence NUMERIC(5,4) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    resolution VARCHAR(50) NULL,
    detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    handled_by BIGINT NULL,
    handled_at TIMESTAMP NULL,
    CONSTRAINT fk_moderation_case_object FOREIGN KEY (object_id) REFERENCES storage_object(object_id) ON DELETE CASCADE,
    CONSTRAINT fk_moderation_case_file FOREIGN KEY (file_id) REFERENCES "file"(file_id) ON DELETE SET NULL,
    CONSTRAINT fk_moderation_case_handled_by FOREIGN KEY (handled_by) REFERENCES "user"(user_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_moderation_case_status_created_at
    ON moderation_case (status, created_at DESC);

DROP TRIGGER IF EXISTS trg_moderation_case_updated_at ON moderation_case;
CREATE TRIGGER trg_moderation_case_updated_at
BEFORE UPDATE ON moderation_case
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS security_event (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NULL,
    session_id BIGINT NULL,
    event_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'info',
    target_type VARCHAR(50) NULL,
    target_id BIGINT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(255) NULL,
    detail JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_security_event_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE SET NULL,
    CONSTRAINT fk_security_event_session FOREIGN KEY (session_id) REFERENCES user_session(session_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_security_event_user_occurred_at
    ON security_event (user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_event_type_occurred_at
    ON security_event (event_type, occurred_at DESC);
