-- =========================
-- Domain: identity
-- Registration email domain regex rules
-- =========================

CREATE TABLE IF NOT EXISTS registration_email_domain_rule (
    rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    pattern VARCHAR(512) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_registration_email_domain_rule_name_ci
    ON registration_email_domain_rule ((LOWER(name)));

CREATE INDEX IF NOT EXISTS idx_registration_email_domain_rule_enabled
    ON registration_email_domain_rule (enabled);

DROP TRIGGER IF EXISTS trg_registration_email_domain_rule_updated_at ON registration_email_domain_rule;
CREATE TRIGGER trg_registration_email_domain_rule_updated_at
BEFORE UPDATE ON registration_email_domain_rule
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
