-- =========================
-- Domain: agent inbox
-- =========================

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agent_inbox_role_enum') THEN
        CREATE TYPE agent_inbox_role_enum AS ENUM ('agent', 'user');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agent_inbox_kind_enum') THEN
        CREATE TYPE agent_inbox_kind_enum AS ENUM (
            'ask',
            'reply',
            'control.pause',
            'control.resume',
            'control.approve',
            'control.deny',
            'control.skip',
            'control.cancel'
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'agent_inbox_status_enum') THEN
        CREATE TYPE agent_inbox_status_enum AS ENUM ('waiting', 'answered', 'timed_out', 'dropped');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS agent_inbox_message (
    inbox_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    role agent_inbox_role_enum NOT NULL,
    kind agent_inbox_kind_enum NOT NULL,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    reply_to_id BIGINT NULL,
    status agent_inbox_status_enum NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    answered_at TIMESTAMP NULL,
    CONSTRAINT fk_agent_inbox_message_job
        FOREIGN KEY (job_id) REFERENCES background_job(job_id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_inbox_message_reply_to
        FOREIGN KEY (reply_to_id) REFERENCES agent_inbox_message(inbox_message_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_agent_inbox_message_job_created
    ON agent_inbox_message (job_id, created_at);

CREATE INDEX IF NOT EXISTS idx_agent_inbox_message_job_status
    ON agent_inbox_message (job_id, status)
    WHERE status IS NOT NULL;
