-- =========================
-- Domain: agent chat sessions
-- =========================

CREATE TABLE IF NOT EXISTS agent_chat_session (
    chat_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    archived BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_chat_session_user
        FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agent_chat_session_user_deleted_updated
    ON agent_chat_session (user_id, deleted_at, updated_at DESC);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'background_job'
          AND column_name = 'chat_session_id'
    ) THEN
        ALTER TABLE background_job ADD COLUMN chat_session_id BIGINT NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'background_job'
          AND column_name = 'deleted_at'
    ) THEN
        ALTER TABLE background_job ADD COLUMN deleted_at TIMESTAMP NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_name = 'background_job'
          AND constraint_name = 'fk_background_job_agent_chat_session'
    ) THEN
        ALTER TABLE background_job
            ADD CONSTRAINT fk_background_job_agent_chat_session
            FOREIGN KEY (chat_session_id)
            REFERENCES agent_chat_session(chat_session_id)
            ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_background_job_chat_session_created
    ON background_job (chat_session_id, created_at)
    WHERE chat_session_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_background_job_chat_session_status
    ON background_job (chat_session_id, status)
    WHERE chat_session_id IS NOT NULL AND deleted_at IS NULL;
