-- =========================
-- Domain: storage and upload
-- =========================

CREATE TABLE IF NOT EXISTS storage_object (
    object_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_hash CHAR(64),
    hash_algorithm VARCHAR(32) NOT NULL DEFAULT 'sha256',
    bucket_name VARCHAR(100) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    object_size BIGINT NOT NULL,
    etag VARCHAR(128),
    version_id VARCHAR(255),
    content_type VARCHAR(255),
    storage_class VARCHAR(50),
    upload_status upload_status_enum NOT NULL DEFAULT 'active',
    scan_status scan_result_enum NOT NULL DEFAULT 'pending',
    moderation_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    quarantined_at TIMESTAMP NULL,
    last_scanned_at TIMESTAMP NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ref_count INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT uk_bucket_object_key UNIQUE (bucket_name, object_key)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_storage_object_hash_algo_size
    ON storage_object (hash_algorithm, object_hash, object_size)
    WHERE object_hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_storage_object_scan_status ON storage_object (scan_status);
CREATE INDEX IF NOT EXISTS idx_storage_object_moderation_status ON storage_object (moderation_status);
CREATE INDEX IF NOT EXISTS idx_storage_object_upload_status ON storage_object(upload_status);

CREATE TRIGGER trg_storage_object_updated_at
BEFORE UPDATE ON storage_object
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS folder (
    folder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    parent_folder_id BIGINT NULL,
    folder_name VARCHAR(255) NOT NULL,
    cached_size BIGINT NOT NULL DEFAULT 0,
    status folder_status_enum NOT NULL DEFAULT 'active',
    folder_type folder_type_enum NOT NULL DEFAULT 'normal',
    deleted_by BIGINT NULL,
    restored_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT fk_folder_owner FOREIGN KEY (owner_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_folder_parent FOREIGN KEY (parent_folder_id) REFERENCES folder(folder_id) ON DELETE CASCADE,
    CONSTRAINT fk_folder_deleted_by FOREIGN KEY (deleted_by) REFERENCES "user"(user_id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_folder_root_name_active
    ON folder (owner_id, folder_name)
    WHERE parent_folder_id IS NULL AND status = 'active';

CREATE UNIQUE INDEX IF NOT EXISTS uk_folder_child_name_active
    ON folder (owner_id, parent_folder_id, folder_name)
    WHERE parent_folder_id IS NOT NULL AND status = 'active';

CREATE INDEX IF NOT EXISTS idx_folder_owner_parent_status ON folder (owner_id, parent_folder_id, status);
CREATE INDEX IF NOT EXISTS idx_folder_name_trgm ON folder USING gin ((LOWER(folder_name)) gin_trgm_ops);

CREATE TRIGGER trg_folder_updated_at
BEFORE UPDATE ON folder
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS "file" (
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    folder_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_ext VARCHAR(50),
    mime_type VARCHAR(255),
    storage_object_id BIGINT NOT NULL,
    file_size BIGINT NOT NULL,
    is_latest BOOLEAN NOT NULL DEFAULT TRUE,
    status file_status_enum NOT NULL DEFAULT 'active',
    deleted_by BIGINT NULL,
    restored_at TIMESTAMP NULL,
    last_accessed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT fk_file_uploader FOREIGN KEY (uploader_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_file_owner FOREIGN KEY (owner_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_file_folder FOREIGN KEY (folder_id) REFERENCES folder(folder_id) ON DELETE CASCADE,
    CONSTRAINT fk_file_storage_object FOREIGN KEY (storage_object_id) REFERENCES storage_object(object_id),
    CONSTRAINT fk_file_deleted_by FOREIGN KEY (deleted_by) REFERENCES "user"(user_id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_file_name_active_in_folder
    ON "file" (owner_id, folder_id, file_name)
    WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_file_last_accessed_at ON "file" (last_accessed_at);
CREATE INDEX IF NOT EXISTS idx_file_name_trgm ON "file" USING gin ((LOWER(file_name)) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_file_storage_object_id ON "file"(storage_object_id);
CREATE INDEX IF NOT EXISTS idx_file_owner_folder ON "file"(owner_id, folder_id, status);

CREATE TRIGGER trg_file_updated_at
BEFORE UPDATE ON "file"
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS upload_task (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    folder_id BIGINT NULL,
    file_name VARCHAR(255) NULL,
    mime_type VARCHAR(255) NULL,
    bucket_name VARCHAR(100) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    object_hash CHAR(64),
    total_size BIGINT NOT NULL,
    chunk_size BIGINT NULL,
    uploaded_bytes BIGINT NOT NULL DEFAULT 0,
    client_file_id VARCHAR(255) NULL,
    upload_id VARCHAR(255),
    upload_mode upload_mode_enum NOT NULL DEFAULT 'single',
    status upload_task_status_enum NOT NULL DEFAULT 'init',
    last_error TEXT NULL,
    completed_at TIMESTAMP NULL,
    expired_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_upload_task_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_upload_task_folder FOREIGN KEY (folder_id) REFERENCES folder(folder_id) ON DELETE SET NULL,
    CONSTRAINT uk_upload_target UNIQUE (bucket_name, object_key, upload_id)
);

CREATE INDEX IF NOT EXISTS idx_upload_task_user_status ON upload_task(user_id, status);
CREATE INDEX IF NOT EXISTS idx_upload_task_expired_at ON upload_task (expired_at);
CREATE UNIQUE INDEX IF NOT EXISTS uk_upload_task_user_client_file_id
    ON upload_task (user_id, client_file_id)
    WHERE client_file_id IS NOT NULL;

CREATE TRIGGER trg_upload_task_updated_at
BEFORE UPDATE ON upload_task
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS upload_task_part (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    part_number INTEGER NOT NULL,
    etag VARCHAR(128),
    part_size BIGINT NOT NULL,
    status upload_part_status_enum NOT NULL DEFAULT 'pending',
    checksum CHAR(64) NULL,
    uploaded_at TIMESTAMP NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_upload_task_part_task FOREIGN KEY (task_id) REFERENCES upload_task(task_id) ON DELETE CASCADE,
    CONSTRAINT uk_task_part UNIQUE (task_id, part_number)
);

CREATE INDEX IF NOT EXISTS idx_upload_task_part_task_status ON upload_task_part (task_id, status);

CREATE TRIGGER trg_upload_task_part_updated_at
BEFORE UPDATE ON upload_task_part
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS file_preview_asset (
    preview_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_object_id BIGINT NOT NULL,
    preview_object_id BIGINT NULL,
    preview_type VARCHAR(50) NOT NULL,
    page_no INTEGER NULL,
    mime_type VARCHAR(255) NULL,
    width INTEGER NULL,
    height INTEGER NULL,
    duration_ms BIGINT NULL,
    status preview_status_enum NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_file_preview_asset_source_object FOREIGN KEY (source_object_id) REFERENCES storage_object(object_id) ON DELETE CASCADE,
    CONSTRAINT fk_file_preview_asset_preview_object FOREIGN KEY (preview_object_id) REFERENCES storage_object(object_id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_file_preview_asset_type_page
    ON file_preview_asset (source_object_id, preview_type, (COALESCE(page_no, -1)));

DROP TRIGGER IF EXISTS trg_file_preview_asset_updated_at ON file_preview_asset;
CREATE TRIGGER trg_file_preview_asset_updated_at
BEFORE UPDATE ON file_preview_asset
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS file_media_metadata (
    metadata_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_object_id BIGINT NOT NULL UNIQUE,
    width INTEGER NULL,
    height INTEGER NULL,
    duration_ms BIGINT NULL,
    page_count INTEGER NULL,
    bitrate INTEGER NULL,
    sample_rate INTEGER NULL,
    video_codec VARCHAR(64) NULL,
    audio_codec VARCHAR(64) NULL,
    extra_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    extracted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_file_media_metadata_source_object FOREIGN KEY (source_object_id) REFERENCES storage_object(object_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS batch_download_task (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    archive_name VARCHAR(255) NOT NULL,
    item_count INTEGER NOT NULL DEFAULT 0,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    storage_object_id BIGINT NULL,
    expire_at TIMESTAMP NULL,
    error_message TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    CONSTRAINT fk_batch_download_task_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_download_task_storage_object FOREIGN KEY (storage_object_id) REFERENCES storage_object(object_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_batch_download_task_user_status
    ON batch_download_task (user_id, status);

DROP TRIGGER IF EXISTS trg_batch_download_task_updated_at ON batch_download_task;
CREATE TRIGGER trg_batch_download_task_updated_at
BEFORE UPDATE ON batch_download_task
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
