-- =========================
-- Domain: worker/background jobs
-- =========================

CREATE TABLE IF NOT EXISTS background_job (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    priority INTEGER NOT NULL DEFAULT 100,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    result JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_message TEXT NULL,
    attempt INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    scheduled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP NULL,
    finished_at TIMESTAMP NULL,
    trace_id VARCHAR(64) NULL,
    idempotency_key VARCHAR(255) NULL,
    agent_phase VARCHAR(32) NULL,
    cancel_requested_at TIMESTAMP NULL,
    requested_by BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_background_job_requested_by FOREIGN KEY (requested_by) REFERENCES "user"(user_id) ON DELETE SET NULL,
    CONSTRAINT uk_background_job_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_background_job_status_scheduled_at ON background_job (status, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_background_job_task_type_status ON background_job (task_type, status);
CREATE INDEX IF NOT EXISTS idx_background_job_requested_by_task_type ON background_job (requested_by, task_type, status);

DROP TRIGGER IF EXISTS trg_background_job_updated_at ON background_job;
CREATE TRIGGER trg_background_job_updated_at
BEFORE UPDATE ON background_job
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
