-- =========================
-- Domain: agent persistence
-- =========================

CREATE TABLE IF NOT EXISTS agent_user_setting (
    setting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    default_execution_policy agent_execution_policy_enum NOT NULL DEFAULT 'confirm',
    default_data_policy_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    llm_provider VARCHAR(50) NULL,
    llm_model VARCHAR(100) NULL,
    default_budget_tokens INTEGER NOT NULL DEFAULT 20000,
    default_max_steps INTEGER NOT NULL DEFAULT 20,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_user_setting_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_agent_user_setting_default_budget_tokens CHECK (default_budget_tokens > 0),
    CONSTRAINT ck_agent_user_setting_default_max_steps CHECK (default_max_steps > 0)
);

CREATE INDEX IF NOT EXISTS idx_agent_user_setting_user_id
    ON agent_user_setting (user_id);

DROP TRIGGER IF EXISTS trg_agent_user_setting_updated_at ON agent_user_setting;
CREATE TRIGGER trg_agent_user_setting_updated_at
BEFORE UPDATE ON agent_user_setting
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS agent_mcp_server (
    mcp_server_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NULL,
    visibility agent_mcp_visibility_enum NOT NULL DEFAULT 'system',
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    endpoint VARCHAR(500) NOT NULL,
    transport VARCHAR(30) NOT NULL DEFAULT 'streamable_http',
    auth_type VARCHAR(30) NOT NULL DEFAULT 'none',
    headers_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    tool_namespace VARCHAR(100) NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_mcp_server_owner FOREIGN KEY (owner_user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_agent_mcp_server_visibility_owner CHECK (
        (visibility = 'system' AND owner_user_id IS NULL)
        OR
        (visibility = 'private' AND owner_user_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_agent_mcp_server_visibility_enabled
    ON agent_mcp_server (visibility, enabled);
CREATE INDEX IF NOT EXISTS idx_agent_mcp_server_owner_visibility
    ON agent_mcp_server (owner_user_id, visibility);

DROP TRIGGER IF EXISTS trg_agent_mcp_server_updated_at ON agent_mcp_server;
CREATE TRIGGER trg_agent_mcp_server_updated_at
BEFORE UPDATE ON agent_mcp_server
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS agent_skill (
    skill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_key VARCHAR(120) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    triggers_text TEXT NULL,
    tool_whitelist_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    plan_template_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    inputs_schema_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    outputs_schema_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    visibility agent_skill_visibility_enum NOT NULL DEFAULT 'global',
    owner_user_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_skill_owner FOREIGN KEY (owner_user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT uk_agent_skill_skill_key UNIQUE (skill_key),
    CONSTRAINT ck_agent_skill_visibility_owner CHECK (
        (visibility = 'global' AND owner_user_id IS NULL)
        OR
        (visibility = 'private' AND owner_user_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_agent_skill_visibility_created_at
    ON agent_skill (visibility, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_skill_owner_visibility
    ON agent_skill (owner_user_id, visibility);
CREATE INDEX IF NOT EXISTS idx_agent_skill_search_trgm
    ON agent_skill
    USING gin ((COALESCE(name, '') || ' ' || COALESCE(description, '') || ' ' || COALESCE(triggers_text, '')) gin_trgm_ops);

DROP TRIGGER IF EXISTS trg_agent_skill_updated_at ON agent_skill;
CREATE TRIGGER trg_agent_skill_updated_at
BEFORE UPDATE ON agent_skill
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS agent_memory (
    memory_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    scope agent_memory_scope_enum NOT NULL,
    scope_key VARCHAR(255) NULL,
    kind agent_memory_kind_enum NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    source_job_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NULL,
    CONSTRAINT fk_agent_memory_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_memory_source_job FOREIGN KEY (source_job_id) REFERENCES background_job(job_id) ON DELETE SET NULL,
    CONSTRAINT ck_agent_memory_scope_key CHECK (
        (scope = 'global' AND scope_key IS NULL)
        OR
        (scope IN ('workspace', 'session') AND scope_key IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_agent_memory_user_scope
    ON agent_memory (user_id, scope, scope_key);
CREATE INDEX IF NOT EXISTS idx_agent_memory_user_expires
    ON agent_memory (user_id, expires_at);
CREATE INDEX IF NOT EXISTS idx_agent_memory_search_trgm
    ON agent_memory
    USING gin ((COALESCE(title, '') || ' ' || COALESCE(content, '')) gin_trgm_ops);

DROP TRIGGER IF EXISTS trg_agent_memory_updated_at ON agent_memory;
CREATE TRIGGER trg_agent_memory_updated_at
BEFORE UPDATE ON agent_memory
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS agent_plan (
    plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    input_text TEXT NOT NULL,
    context_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    execution_policy agent_execution_policy_enum NOT NULL,
    data_policy_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    chosen_skill_id VARCHAR(120) NULL,
    proposed_actions_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    plan_hash VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    cost_estimate_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_agent_plan_job FOREIGN KEY (job_id) REFERENCES background_job(job_id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_plan_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agent_plan_user_created_at
    ON agent_plan (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_plan_plan_hash
    ON agent_plan (plan_hash);

CREATE TABLE IF NOT EXISTS agent_action_log (
    action_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    step_no INTEGER NOT NULL,
    tool_name VARCHAR(120) NOT NULL,
    inputs_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    outputs_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    duration_ms INTEGER NULL,
    error_message TEXT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP NULL,
    CONSTRAINT fk_agent_action_log_job FOREIGN KEY (job_id) REFERENCES background_job(job_id) ON DELETE CASCADE,
    CONSTRAINT uk_agent_action_log_job_step UNIQUE (job_id, step_no)
);

CREATE INDEX IF NOT EXISTS idx_agent_action_log_job_started_at
    ON agent_action_log (job_id, started_at);
CREATE INDEX IF NOT EXISTS idx_agent_action_log_job_status
    ON agent_action_log (job_id, status);

CREATE TABLE IF NOT EXISTS agent_work_session (
    work_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    checkpoint_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    checkpoint_version INTEGER NOT NULL DEFAULT 0,
    last_checkpoint_at TIMESTAMP NULL,
    tool_call_count INTEGER NOT NULL DEFAULT 0,
    last_tool_started_at TIMESTAMP NULL,
    last_tool_finished_at TIMESTAMP NULL,
    last_error_message TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP NULL,
    CONSTRAINT fk_agent_work_session_job FOREIGN KEY (job_id) REFERENCES background_job(job_id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_work_session_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_agent_work_session_checkpoint_version CHECK (checkpoint_version >= 0),
    CONSTRAINT ck_agent_work_session_tool_call_count CHECK (tool_call_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_agent_work_session_user_status
    ON agent_work_session (user_id, status);
CREATE INDEX IF NOT EXISTS idx_agent_work_session_created_at
    ON agent_work_session (created_at DESC);

DROP TRIGGER IF EXISTS trg_agent_work_session_updated_at ON agent_work_session;
CREATE TRIGGER trg_agent_work_session_updated_at
BEFORE UPDATE ON agent_work_session
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- Agent views and functions
-- =========================

CREATE OR REPLACE FUNCTION agent_refresh_work_session_metrics(p_work_session_id BIGINT)
RETURNS VOID AS $$
BEGIN
    IF p_work_session_id IS NULL THEN
        RETURN;
    END IF;

    UPDATE agent_work_session aws
    SET tool_call_count = COALESCE(agg.tool_call_count, 0),
        last_tool_started_at = agg.last_tool_started_at,
        last_tool_finished_at = agg.last_tool_finished_at,
        last_error_message = agg.last_error_message
    FROM (
        SELECT
            ws.work_session_id,
            COUNT(al.action_log_id)::INTEGER AS tool_call_count,
            MAX(al.started_at) AS last_tool_started_at,
            MAX(al.finished_at) AS last_tool_finished_at,
            (
                SELECT sub.error_message
                FROM agent_action_log sub
                WHERE sub.job_id = ws.job_id
                  AND sub.error_message IS NOT NULL
                ORDER BY COALESCE(sub.finished_at, sub.started_at) DESC, sub.action_log_id DESC
                LIMIT 1
            ) AS last_error_message
        FROM agent_work_session ws
        LEFT JOIN agent_action_log al ON al.job_id = ws.job_id
        WHERE ws.work_session_id = p_work_session_id
        GROUP BY ws.work_session_id, ws.job_id
    ) agg
    WHERE aws.work_session_id = agg.work_session_id;
END;
$$ LANGUAGE plpgsql;

DROP VIEW IF EXISTS v_agent_job_overview;
DROP VIEW IF EXISTS v_agent_memory_active;
DROP VIEW IF EXISTS v_agent_mcp_catalog;
DROP VIEW IF EXISTS v_agent_skill_catalog;

CREATE VIEW v_agent_skill_catalog AS
SELECT
    s.skill_id,
    s.skill_key,
    s.name,
    s.description,
    s.triggers_text,
    s.tool_whitelist_json,
    s.plan_template_json,
    s.inputs_schema_json,
    s.outputs_schema_json,
    s.visibility,
    s.owner_user_id,
    s.created_at,
    s.updated_at,
    (COALESCE(s.name, '') || ' ' || COALESCE(s.description, '') || ' ' || COALESCE(s.triggers_text, '')) AS search_text
FROM agent_skill s;

CREATE VIEW v_agent_mcp_catalog AS
SELECT
    m.mcp_server_id,
    m.name,
    m.description,
    m.endpoint,
    m.transport,
    m.auth_type,
    m.headers_json,
    m.tool_namespace,
    m.enabled,
    m.metadata_json,
    m.visibility,
    m.owner_user_id,
    m.created_at,
    m.updated_at
FROM agent_mcp_server m;

CREATE VIEW v_agent_memory_active AS
SELECT
    am.memory_id,
    am.user_id,
    am.scope,
    am.scope_key,
    am.kind,
    am.title,
    am.content,
    am.source_job_id,
    am.created_at,
    am.updated_at,
    am.expires_at
FROM agent_memory am
WHERE am.expires_at IS NULL
   OR am.expires_at > CURRENT_TIMESTAMP;

CREATE VIEW v_agent_job_overview AS
SELECT
    bj.job_id,
    bj.task_type,
    bj.status,
    bj.agent_phase,
    bj.cancel_requested_at,
    bj.requested_by AS user_id,
    bj.priority,
    bj.trace_id,
    bj.created_at,
    bj.updated_at,
    bj.started_at,
    bj.finished_at,
    ap.plan_id,
    ap.plan_hash,
    ap.summary AS plan_summary,
    ap.chosen_skill_id,
    aws.work_session_id,
    aws.status AS work_session_status,
    aws.checkpoint_version,
    aws.last_checkpoint_at,
    aws.tool_call_count,
    aws.last_tool_started_at,
    aws.last_tool_finished_at,
    aws.last_error_message,
    COALESCE(al.action_count, 0) AS action_count
FROM background_job bj
LEFT JOIN agent_plan ap ON ap.job_id = bj.job_id
LEFT JOIN agent_work_session aws ON aws.job_id = bj.job_id
LEFT JOIN (
    SELECT job_id, COUNT(*) AS action_count
    FROM agent_action_log
    GROUP BY job_id
) al ON al.job_id = bj.job_id;

-- =========================
-- Agent comments
-- =========================

COMMENT ON TABLE agent_user_setting IS 'Agent default settings per user';
COMMENT ON COLUMN agent_user_setting.setting_id IS 'Primary key';
COMMENT ON COLUMN agent_user_setting.user_id IS 'Owner user id';
COMMENT ON COLUMN agent_user_setting.default_execution_policy IS 'Default execution policy';
COMMENT ON COLUMN agent_user_setting.default_data_policy_json IS 'Default data policy payload';
COMMENT ON COLUMN agent_user_setting.llm_provider IS 'Default LLM provider';
COMMENT ON COLUMN agent_user_setting.llm_model IS 'Default LLM model';
COMMENT ON COLUMN agent_user_setting.default_budget_tokens IS 'Default token budget';
COMMENT ON COLUMN agent_user_setting.default_max_steps IS 'Default max steps';

COMMENT ON TABLE agent_mcp_server IS 'Visible MCP server configuration for agents';
COMMENT ON COLUMN agent_mcp_server.mcp_server_id IS 'Primary key';
COMMENT ON COLUMN agent_mcp_server.owner_user_id IS 'Private MCP owner user id';
COMMENT ON COLUMN agent_mcp_server.visibility IS 'Visibility level (system/private)';
COMMENT ON COLUMN agent_mcp_server.endpoint IS 'MCP endpoint';
COMMENT ON COLUMN agent_mcp_server.transport IS 'MCP transport';
COMMENT ON COLUMN agent_mcp_server.auth_type IS 'Auth strategy';
COMMENT ON COLUMN agent_mcp_server.headers_json IS 'Headers payload';
COMMENT ON COLUMN agent_mcp_server.metadata_json IS 'Additional metadata';

COMMENT ON TABLE agent_skill IS 'Persisted agent skill definitions';
COMMENT ON COLUMN agent_skill.skill_id IS 'Primary key';
COMMENT ON COLUMN agent_skill.skill_key IS 'Stable skill key';
COMMENT ON COLUMN agent_skill.triggers_text IS 'Skill trigger description';
COMMENT ON COLUMN agent_skill.tool_whitelist_json IS 'Tool whitelist';
COMMENT ON COLUMN agent_skill.plan_template_json IS 'Plan template payload';
COMMENT ON COLUMN agent_skill.inputs_schema_json IS 'Input schema payload';
COMMENT ON COLUMN agent_skill.outputs_schema_json IS 'Output schema payload';
COMMENT ON COLUMN agent_skill.visibility IS 'Visibility level (global/private)';
COMMENT ON COLUMN agent_skill.owner_user_id IS 'Private skill owner user id';

COMMENT ON TABLE agent_memory IS 'Agent memory items';
COMMENT ON COLUMN agent_memory.memory_id IS 'Primary key';
COMMENT ON COLUMN agent_memory.scope IS 'Memory scope';
COMMENT ON COLUMN agent_memory.scope_key IS 'Workspace folder id or session job id';
COMMENT ON COLUMN agent_memory.kind IS 'Memory kind';
COMMENT ON COLUMN agent_memory.source_job_id IS 'Source job id';
COMMENT ON COLUMN agent_memory.expires_at IS 'Optional expiration time';

COMMENT ON TABLE agent_plan IS 'Persisted agent plans';
COMMENT ON COLUMN agent_plan.plan_id IS 'Primary key';
COMMENT ON COLUMN agent_plan.job_id IS 'Owning background job id';
COMMENT ON COLUMN agent_plan.context_json IS 'Planning context payload';
COMMENT ON COLUMN agent_plan.data_policy_json IS 'Planning data policy payload';
COMMENT ON COLUMN agent_plan.chosen_skill_id IS 'Chosen skill key';
COMMENT ON COLUMN agent_plan.proposed_actions_json IS 'Plan DSL payload';
COMMENT ON COLUMN agent_plan.plan_hash IS 'Plan hash';
COMMENT ON COLUMN agent_plan.cost_estimate_json IS 'Estimated cost payload';

COMMENT ON TABLE agent_action_log IS 'Step-level tool execution log for agent jobs';
COMMENT ON COLUMN agent_action_log.action_log_id IS 'Primary key';
COMMENT ON COLUMN agent_action_log.step_no IS 'Plan step number';
COMMENT ON COLUMN agent_action_log.inputs_json IS 'Tool inputs';
COMMENT ON COLUMN agent_action_log.outputs_json IS 'Tool outputs';
COMMENT ON COLUMN agent_action_log.duration_ms IS 'Execution duration in milliseconds';

COMMENT ON TABLE agent_work_session IS 'Current work session snapshot for an agent job';
COMMENT ON COLUMN agent_work_session.work_session_id IS 'Primary key';
COMMENT ON COLUMN agent_work_session.job_id IS 'Owning background job id';
COMMENT ON COLUMN agent_work_session.checkpoint_json IS 'Latest checkpoint snapshot';
COMMENT ON COLUMN agent_work_session.checkpoint_version IS 'Checkpoint version';
COMMENT ON COLUMN agent_work_session.tool_call_count IS 'Aggregated tool call count';
COMMENT ON COLUMN agent_work_session.last_error_message IS 'Latest tool error summary';

COMMENT ON VIEW v_agent_skill_catalog IS 'Visible agent skill catalog';
COMMENT ON VIEW v_agent_mcp_catalog IS 'Visible MCP catalog';
COMMENT ON VIEW v_agent_memory_active IS 'Unexpired agent memory';
COMMENT ON VIEW v_agent_job_overview IS 'Aggregated agent job overview';
