-- PostgreSQL version of schema-mariadb.sql

-- PostgreSQL 里通常先手动创建数据库，再连接进去执行下面脚本：
-- CREATE DATABASE kepan;
-- \c kepan

-- =========================
-- Enum types
-- =========================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'upload_status_enum') THEN
        CREATE TYPE upload_status_enum AS ENUM ('uploading', 'active', 'deleted', 'failed');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'folder_status_enum') THEN
        CREATE TYPE folder_status_enum AS ENUM ('active', 'deleted');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'file_status_enum') THEN
        CREATE TYPE file_status_enum AS ENUM ('active', 'deleted');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'upload_mode_enum') THEN
        CREATE TYPE upload_mode_enum AS ENUM ('single', 'multipart');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'upload_task_status_enum') THEN
        CREATE TYPE upload_task_status_enum AS ENUM ('init', 'uploading', 'completed', 'aborted', 'failed');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'upload_part_status_enum') THEN
        CREATE TYPE upload_part_status_enum AS ENUM ('pending', 'uploaded');
    END IF;
END
$$;

-- =========================
-- updated_at trigger
-- =========================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================
-- 用户表
-- =========================
CREATE TABLE IF NOT EXISTS "user" (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'USER',
    storage_limit BIGINT NOT NULL DEFAULT 10737418240,
    storage_used BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_username UNIQUE (username),
    CONSTRAINT uk_email UNIQUE (email)
);

CREATE TRIGGER trg_user_updated_at
BEFORE UPDATE ON "user"
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- 用户组
-- =========================
CREATE TABLE IF NOT EXISTS user_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_group_member (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'member',
    CONSTRAINT fk_ugm_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_ugm_group FOREIGN KEY (group_id) REFERENCES user_group(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_group UNIQUE (user_id, group_id)
);

-- =========================
-- 存储对象表
-- =========================
CREATE TABLE IF NOT EXISTS storage_object (
    object_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_hash CHAR(64) NOT NULL,
    bucket_name VARCHAR(100) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    object_size BIGINT NOT NULL,
    etag VARCHAR(128),
    version_id VARCHAR(255),
    content_type VARCHAR(255),
    storage_class VARCHAR(50),
    upload_status upload_status_enum NOT NULL DEFAULT 'active',
    ref_count INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT uk_object_hash UNIQUE (object_hash),
    CONSTRAINT uk_bucket_object_key UNIQUE (bucket_name, object_key)
);

CREATE INDEX IF NOT EXISTS idx_storage_object_upload_status
ON storage_object(upload_status);

CREATE TRIGGER trg_storage_object_updated_at
BEFORE UPDATE ON storage_object
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- 文件夹表
-- =========================
CREATE TABLE IF NOT EXISTS folder (
    folder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    parent_folder_id BIGINT NULL,
    folder_name VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL DEFAULT 0,
    status folder_status_enum NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT fk_folder_owner FOREIGN KEY (owner_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_folder_parent FOREIGN KEY (parent_folder_id) REFERENCES folder(folder_id) ON DELETE CASCADE,
    CONSTRAINT uk_folder_name_in_parent UNIQUE (parent_folder_id, folder_name, owner_id, status)
);

CREATE TRIGGER trg_folder_updated_at
BEFORE UPDATE ON folder
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- 文件表
-- =========================
CREATE TABLE IF NOT EXISTS "file" (
    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploader_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    folder_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_ext VARCHAR(50),
    mime_type VARCHAR(255),
    storage_object_id BIGINT NOT NULL,
    file_size BIGINT NOT NULL,
    is_latest BOOLEAN NOT NULL DEFAULT TRUE,
    status file_status_enum NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT fk_file_uploader FOREIGN KEY (uploader_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_file_owner FOREIGN KEY (owner_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_file_folder FOREIGN KEY (folder_id) REFERENCES folder(folder_id) ON DELETE CASCADE,
    CONSTRAINT fk_file_storage_object FOREIGN KEY (storage_object_id) REFERENCES storage_object(object_id),
    CONSTRAINT uk_file_name_in_folder UNIQUE (folder_id, file_name, owner_id, status)
);

CREATE INDEX IF NOT EXISTS idx_file_storage_object_id
ON "file"(storage_object_id);

CREATE INDEX IF NOT EXISTS idx_file_owner_folder
ON "file"(owner_id, folder_id, status);

CREATE TRIGGER trg_file_updated_at
BEFORE UPDATE ON "file"
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- ACL
-- =========================
CREATE TABLE IF NOT EXISTS acl (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NULL,
    folder_id BIGINT NULL,
    user_id BIGINT NULL,
    group_id BIGINT NULL,
    permission VARCHAR(100) NOT NULL,
    CONSTRAINT fk_acl_file FOREIGN KEY (file_id) REFERENCES "file"(file_id) ON DELETE CASCADE,
    CONSTRAINT fk_acl_folder FOREIGN KEY (folder_id) REFERENCES folder(folder_id) ON DELETE CASCADE,
    CONSTRAINT fk_acl_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_acl_group FOREIGN KEY (group_id) REFERENCES user_group(id) ON DELETE CASCADE,
    CONSTRAINT chk_acl_target CHECK (
        (user_id IS NOT NULL OR group_id IS NOT NULL)
        AND
        (file_id IS NOT NULL OR folder_id IS NOT NULL)
    )
);

-- =========================
-- 分享表
-- =========================
CREATE TABLE IF NOT EXISTS share (
    share_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    file_id BIGINT NULL,
    folder_id BIGINT NULL,
    share_link VARCHAR(255) NOT NULL UNIQUE,
    share_type VARCHAR(50) NOT NULL DEFAULT 'public',
    password_hash VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expire_time TIMESTAMP NULL,
    visit_count INTEGER NOT NULL DEFAULT 0,
    download_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_share_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_share_file FOREIGN KEY (file_id) REFERENCES "file"(file_id) ON DELETE CASCADE,
    CONSTRAINT fk_share_folder FOREIGN KEY (folder_id) REFERENCES folder(folder_id) ON DELETE CASCADE,
    CONSTRAINT chk_share_target CHECK (
        (file_id IS NOT NULL AND folder_id IS NULL)
        OR
        (file_id IS NULL AND folder_id IS NOT NULL)
    )
);

-- =========================
-- 日志表
-- =========================
CREATE TABLE IF NOT EXISTS "log" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    operation VARCHAR(255) NOT NULL,
    details TEXT,
    ip_address VARCHAR(45),
    performed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_log_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE
);

-- =========================
-- 通知表
-- =========================
CREATE TABLE IF NOT EXISTS notification (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message VARCHAR(255) NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE
);

-- =========================
-- 视图 v_file_folder_details
-- =========================
CREATE OR REPLACE VIEW v_file_folder_details AS
SELECT
    'file' AS item_type,
    f.file_id AS id,
    f.file_name AS name,
    so.object_size AS size,
    f.mime_type,
    f.folder_id AS parent_id,
    f.owner_id AS owner_id,
    u.username AS owner_name,
    f.created_at,
    f.updated_at
FROM "file" f
JOIN "user" u ON f.owner_id = u.user_id
JOIN storage_object so ON f.storage_object_id = so.object_id
WHERE f.status = 'active' AND so.upload_status = 'active'
UNION ALL
SELECT
    'folder' AS item_type,
    fo.folder_id AS id,
    fo.folder_name AS name,
    fo.size,
    'inode/directory' AS mime_type,
    fo.parent_folder_id AS parent_id,
    fo.owner_id AS owner_id,
    u.username AS owner_name,
    fo.created_at,
    fo.updated_at
FROM folder fo
JOIN "user" u ON fo.owner_id = u.user_id
WHERE fo.status = 'active';

-- =========================
-- 视图 v_user_permissions
-- =========================
CREATE OR REPLACE VIEW v_user_permissions AS
SELECT
    acl.id AS acl_id,
    u.user_id AS user_id,
    u.username AS user_name,
    COALESCE(f.file_id, fl.folder_id) AS item_id,
    COALESCE(f.file_name, fl.folder_name) AS item_name,
    CASE
        WHEN f.file_id IS NOT NULL THEN 'file'
        ELSE 'folder'
    END AS item_type,
    acl.permission
FROM acl
JOIN "user" u ON acl.user_id = u.user_id
LEFT JOIN "file" f ON acl.file_id = f.file_id
LEFT JOIN folder fl ON acl.folder_id = fl.folder_id
WHERE acl.user_id IS NOT NULL;

-- =========================
-- 视图 v_user_storage_summary
-- =========================
CREATE OR REPLACE VIEW v_user_storage_summary AS
SELECT
    user_id,
    username,
    storage_limit,
    storage_used
FROM "user";

-- =========================
-- 视图 v_shared_with_me
-- =========================
CREATE OR REPLACE VIEW v_shared_with_me AS
SELECT
    vffd.item_type,
    vffd.id AS item_id,
    vffd.name AS item_name,
    vffd.owner_name AS shared_by,
    acl.permission,
    ugm.user_id AS shared_to_user_id
FROM acl
JOIN user_group_member ugm ON acl.group_id = ugm.group_id
JOIN v_file_folder_details vffd
    ON (
        acl.file_id IS NOT NULL AND vffd.item_type = 'file' AND acl.file_id = vffd.id
    ) OR (
        acl.folder_id IS NOT NULL AND vffd.item_type = 'folder' AND acl.folder_id = vffd.id
    )
WHERE acl.group_id IS NOT NULL

UNION

SELECT
    vffd.item_type,
    vffd.id AS item_id,
    vffd.name AS item_name,
    vffd.owner_name AS shared_by,
    acl.permission,
    acl.user_id AS shared_to_user_id
FROM acl
JOIN v_file_folder_details vffd
    ON (
        acl.file_id IS NOT NULL AND vffd.item_type = 'file' AND acl.file_id = vffd.id
    ) OR (
        acl.folder_id IS NOT NULL AND vffd.item_type = 'folder' AND acl.folder_id = vffd.id
    )
WHERE acl.user_id IS NOT NULL;

-- =========================
-- 视图 v_full_path
-- =========================
CREATE OR REPLACE VIEW v_full_path AS
WITH RECURSIVE folder_path (id, name, path) AS (
    SELECT
        folder_id,
        folder_name,
        CAST(folder_name AS VARCHAR(2048))
    FROM folder
    WHERE parent_folder_id IS NULL

    UNION ALL

    SELECT
        f.folder_id,
        f.folder_name,
        fp.path || '/' || f.folder_name
    FROM folder f
    JOIN folder_path fp ON f.parent_folder_id = fp.id
)
SELECT id, path
FROM folder_path;

-- =========================
-- 视图 v_user_recycle_bin
-- 注意：原 SQL 这里有明显字段不一致问题，我按现有表结构修正为可执行版本
-- =========================
CREATE OR REPLACE VIEW v_user_recycle_bin AS
SELECT
    'file' AS item_type,
    f.file_id AS id,
    f.file_name AS name,
    so.object_size AS size,
    f.folder_id AS parent_id,
    f.uploader_id AS owner_id,
    u.username AS owner_name,
    f.deleted_at
FROM "file" f
JOIN "user" u ON f.uploader_id = u.user_id
JOIN storage_object so ON f.storage_object_id = so.object_id
WHERE f.status = 'deleted' AND f.deleted_at IS NOT NULL

UNION ALL

SELECT
    'folder' AS item_type,
    fo.folder_id AS id,
    fo.folder_name AS name,
    fo.size,
    fo.parent_folder_id AS parent_id,
    fo.owner_id AS owner_id,
    u.username AS owner_name,
    fo.deleted_at
FROM folder fo
JOIN "user" u ON fo.owner_id = u.user_id
WHERE fo.status = 'deleted' AND fo.deleted_at IS NOT NULL;

-- =========================
-- 上传任务表
-- =========================
CREATE TABLE IF NOT EXISTS upload_task (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    bucket_name VARCHAR(100) NOT NULL,
    object_key VARCHAR(1024) NOT NULL,
    object_hash CHAR(64),
    total_size BIGINT NOT NULL,
    upload_id VARCHAR(255),
    upload_mode upload_mode_enum NOT NULL DEFAULT 'single',
    status upload_task_status_enum NOT NULL DEFAULT 'init',
    expired_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_upload_task_user FOREIGN KEY (user_id) REFERENCES "user"(user_id) ON DELETE CASCADE,
    CONSTRAINT uk_upload_target UNIQUE (bucket_name, object_key, upload_id)
);

CREATE INDEX IF NOT EXISTS idx_upload_task_user_status
ON upload_task(user_id, status);

CREATE TRIGGER trg_upload_task_updated_at
BEFORE UPDATE ON upload_task
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =========================
-- 上传分片表
-- =========================
CREATE TABLE IF NOT EXISTS upload_task_part (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    part_number INTEGER NOT NULL,
    etag VARCHAR(128),
    part_size BIGINT NOT NULL,
    status upload_part_status_enum NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_upload_task_part_task FOREIGN KEY (task_id) REFERENCES upload_task(task_id) ON DELETE CASCADE,
    CONSTRAINT uk_task_part UNIQUE (task_id, part_number)
);

CREATE TRIGGER trg_upload_task_part_updated_at
BEFORE UPDATE ON upload_task_part
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();